runtime: python311
service: codedpad-main
module: default

handlers:

- url: /static
  static_dir: static


- url: /.*
  script: main.py

env_variables:
  mail: "30nithinms@gmail.com"
  url: "mongodb+srv://msnithin84:Nithin@cluster0.wob2cfi.mongodb.net/coded"

  